info:
    serviceLinks:
        api-doc: "${route.name}/docs/index.html"
    dependencies:
        skatteetaten: "skatteetaten"

spring:
    application:
        name: fergus
    profiles:
        active: local

logging:
    level:
        ske.aurora: INFO
        no.skatteetaten: INFO
        org:
            springframework: WARN
            apache.catalina: WARN
            hibernate: WARN

integrations:
    storagegrid:
        url: http://storagegrid

---

spring:
    config:
        activate:
            on-profile: openshift

aurora:
    token:
        location: /u01/secrets/app/aurora-token/token

---

spring:
    config:
        activate:
            on-profile: local

#    datasource:
#        url: ${refapp.datasource.url:jdbc:oracle:thin:@host:port/path}
#        username: ${refapp.datasource.username:username}
#        password: ${refapp.datasource.password:password}

aurora.token.value: token

management:
    server.port: 8081


logging:
    pattern:
        console: "%d [%-9.9thread] %-5level %logger %X - %msg %n%rEx{full}"

integrations:
    storagegrid:
        url: "https://uia0ins-netapp-storagegrid01.skead.no/"

