info:
    dependencies:
        skatteetaten: "skatteetaten"

spring:
    application:
        name: fergus
    profiles:
        active: local
    jackson:
        # Necessary to avoid inclusion of entries with null or empty listvalues in S3 policies, which will violate rules in StorageGRID
        default-property-inclusion: non_empty

logging:
    level:
        ske.aurora: INFO
        no.skatteetaten: INFO
        org:
            springframework: WARN
            apache.catalina: WARN
            hibernate: WARN

fergus:
    ssl:
        trustmanagerinsecure: ${FERGUS_TRUSTMANAGERINSECURE:false}
    provision:
        user:
            randompass: ${FERGUS_RANDOMPASS:true}
            defaultpass: ${FERGUS_DEFAULT_PASSWORD:S3userpass}

integrations:
    storagegrid:
        url: ${FERGUS_MANAGEMENT_URL:http://storagegrid}
        s3url: ${FERGUS_S3_URL:http://uia0ins-netapp-storagegrid01.skead.no:10880/}
        bucketregion: ${FERGUS_S3_REGION:no-skatt-1}

---

spring:
    config:
        activate:
            on-profile: openshift

aurora:
    token:
        location: /u01/secrets/app/aurora-token/token

---

spring:
    config:
        activate:
            on-profile: local

aurora.token.value: token

management:
    server.port: 8081


logging:
    pattern:
        console: "%d [%-9.9thread] %-5level %logger %X - %msg %n%rEx{full}"

integrations:
    storagegrid:
        url: ${FERGUS_MANAGEMENT_URL:https://uia0ins-netapp-storagegrid01.skead.no/}
        s3url: ${FERGUS_S3_URL:http://uia0ins-netapp-storagegrid01.skead.no:10880/}

